version: "2.4"

services:
  telegram_bot_mpei:
    build: ./
    command: ./wait-for-postgres.sh db ./telegram_bot_mpei
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    restart: always
    image: postgres:13.3
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
